[window]
opacity = 0.50
title = "Alacritty"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 12.0

[terminal.shell]
program = "/usr/bin/fish"

[colors.primary]
background = "0x000000"
foreground = "0xf8f8f2"

[colors.normal]
black = "0x000000"
red = "0xff5774"
green = "0x6ae98a"
yellow = "0xffe099"
blue = "0xff7a99"
magenta = "0xe0b2a5"
cyan = "0xefdaa1"
white = "0xbfbfbf"

[colors.bright]
black = "0x4d4d4d"
red = "0xff6580"
green = "0x70f893"
yellow = "0xffe6ad"
blue = "0xff8ba6"
magenta = "0xe8c4bb"
cyan = "0xffe8ac"
white = "0xe6e6e6"

#[[keyboard.bindings]]
#key = "C"
#mods = "Control"
#action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"
